In [21]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

In [3]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [4]:
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [5]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [6]:
planets.info()

<class 'pandas.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   method          1035 non-null   str
 1   number          1035 non-null   int64
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64
dtypes: float64(3), int64(2), str(1)
memory usage: 48.6 KB

In [7]:
planets.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [8]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'],'data':range(6)},columns = ['key','data'])
df

  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [9]:
df.groupby('key')

In [10]:
df.groupby('key').sum()

     data
key
A       3
B       5
C       7

In [11]:
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [12]:
grouped_data = planets.groupby('method')['orbital_period'].median()
grouped_data

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [13]:
grouped_data_1 = planets.groupby('method')[['orbital_period','mass']].median()
grouped_data_1

                               orbital_period   mass
method
Astrometry                         631.180000    NaN
Eclipse Timing Variations         4343.500000  5.125
Imaging                          27500.000000    NaN
Microlensing                      3300.000000    NaN
Orbital Brightness Modulation        0.342887    NaN
Pulsar Timing                       66.541900    NaN
Pulsation Timing Variations       1170.000000    NaN
Radial Velocity                    360.200000  1.260
Transit                              5.714932  1.470
Transit Timing Variations           57.011000    NaN

In [18]:
planets['method'].unique()

<StringArray>
[              'Radial Velocity',                       'Imaging',
     'Eclipse Timing Variations',                       'Transit',
                    'Astrometry',     'Transit Timing Variations',
 'Orbital Brightness Modulation',                  'Microlensing',
                 'Pulsar Timing',   'Pulsation Timing Variations']
Length: 10, dtype: str

In [19]:
planets.groupby('method').size()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
dtype: int64

In [20]:
planets.groupby('method')['year'].describe().unstack()

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

In [23]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key':['A','B','C','A','B','C'], 
                   'data1':range(6),
                   'data2':rng.randint(0,10,6)}, 
                   columns = ['key','data1','data2'])
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [26]:
df.groupby('key').aggregate(['min',np.median,max])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [27]:
df.head()

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7

In [28]:
def filter_func(x):
    return x['data2'].std() > 4
display("df","df.groupby('key').std()","df.groupby('key').filter(filter_func)")

df
  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

df.groupby('key').std()
       data1     data2
key
A    2.12132  1.414214
B    2.12132  4.949747
C    2.12132  4.242641

df.groupby('key').filter(filter_func)
  key  data1  data2
1   B      1      0
2   C      2      3
4   B      4      7
5   C      5      9