# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [6]:
import pandas as pd
import yfinance as yf
import numpy as np

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [12]:
period = pd.date_range('01/01/2015',pd.Timestamp.now().date())
period

DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
               '2015-01-05', '2015-01-06', '2015-01-07', '2015-01-08',
               '2015-01-09', '2015-01-10',
               ...
               '2026-03-23', '2026-03-24', '2026-03-25', '2026-03-26',
               '2026-03-27', '2026-03-28', '2026-03-29', '2026-03-30',
               '2026-03-31', '2026-04-01'],
              dtype='datetime64[us]', length=4109, freq='D')

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [20]:
# Linkedin had been delisted from stock exchange in 2016 and twitter in 2022 so I wont be using them
stocks = ['AAPL','TSLA','IBM']

### Step 4. Read the data from google, assign to df and print it

In [21]:
df = yf.download(stocks, start='2015-01-01', end=pd.Timestamp.now().date())
df

[*********************100%***********************]  3 of 3 completed

Price            Close                                High              \
Ticker            AAPL         IBM        TSLA        AAPL         IBM
Date
2015-01-02   24.214886   97.566780   14.620667   24.682218   98.319337
2015-01-05   23.532722   96.031578   14.006000   24.064285   97.091171
2015-01-06   23.534929   93.960541   14.085333   23.794066   96.302483
2015-01-07   23.864948   93.346451   14.063333   23.964616   94.640840
2015-01-08   24.781893   95.375359   14.041333   24.839479   95.748620
...                ...         ...         ...         ...         ...
2026-03-25  252.619995  241.389999  385.950012  255.000000  246.190002
2026-03-26  252.889999  241.669998  372.109985  257.000000  246.669998
2026-03-27  248.800003  236.339996  361.829987  255.490005  239.440002
2026-03-30  246.630005  237.250000  355.279999  250.869995  240.210007
2026-03-31  253.789993  242.389999  371.750000  255.479996  242.850006

Price                          Low                                Open  \
Ticker            TSLA        AAPL         IBM        TSLA        AAPL
Date
2015-01-02   14.883333   23.776346   96.928618   14.217333   24.671143
2015-01-05   14.433333   23.346676   95.838927   13.810667   23.984551
2015-01-06   14.280000   23.173909   93.418709   13.614000   23.596945
2015-01-07   14.318667   23.632389   92.732369   13.985333   23.743131
2015-01-08   14.253333   24.075357   93.647498   14.000667   24.192745
...                ...         ...         ...         ...         ...
2026-03-25  396.230011  251.600006  238.000000  385.010010  254.100006
2026-03-26  384.440002  250.770004  239.800003  371.869995  252.119995
2026-03-27  369.859985  248.070007  233.750000  359.470001  253.899994
2026-03-30  367.290009  245.509995  236.130005  352.140015  250.070007
2026-03-31  373.329987  247.100006  236.380005  361.000000  247.910004

Price                                  Volume
Ticker             IBM        TSLA       AAPL      IBM      TSLA
Date
2015-01-02   97.115253   14.858000  212818400  5779673  71466000
2015-01-05   97.091171   14.303333  257142000  5104898  80527500
2015-01-06   96.127887   14.004000  263188400  6429448  93928500
2015-01-07   94.640840   14.223333  160423600  4918083  44526000
2015-01-08   94.062905   14.187333  237458000  4431693  51637500
...                ...         ...        ...      ...       ...
2026-03-25  243.600006  389.989990   28476700  4207900  55157300
2026-03-26  240.559998  381.600006   41796700  3606800  55522900
2026-03-27  238.850006  369.690002   47900000  4853700  62065700
2026-03-30  237.800003  365.859985   39446200  3882600  67954400
2026-03-31  240.270004  361.510010   49549600  4747000  75289300

[2827 rows x 15 columns]

### Step 5.  What is the type of structure of df ?

In [22]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2827 entries, 2015-01-02 to 2026-03-31
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2827 non-null   float64
 1   (Close, IBM)    2827 non-null   float64
 2   (Close, TSLA)   2827 non-null   float64
 3   (High, AAPL)    2827 non-null   float64
 4   (High, IBM)     2827 non-null   float64
 5   (High, TSLA)    2827 non-null   float64
 6   (Low, AAPL)     2827 non-null   float64
 7   (Low, IBM)      2827 non-null   float64
 8   (Low, TSLA)     2827 non-null   float64
 9   (Open, AAPL)    2827 non-null   float64
 10  (Open, IBM)     2827 non-null   float64
 11  (Open, TSLA)    2827 non-null   float64
 12  (Volume, AAPL)  2827 non-null   int64
 13  (Volume, IBM)   2827 non-null   int64
 14  (Volume, TSLA)  2827 non-null   int64
dtypes: float64(12), int64(3)
memory usage: 353.4 KB

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

In [23]:
vol = pd.DataFrame(df['Volume'])
vol

Ticker           AAPL      IBM      TSLA
Date
2015-01-02  212818400  5779673  71466000
2015-01-05  257142000  5104898  80527500
2015-01-06  263188400  6429448  93928500
2015-01-07  160423600  4918083  44526000
2015-01-08  237458000  4431693  51637500
...               ...      ...       ...
2026-03-25   28476700  4207900  55157300
2026-03-26   41796700  3606800  55522900
2026-03-27   47900000  4853700  62065700
2026-03-30   39446200  3882600  67954400
2026-03-31   49549600  4747000  75289300

[2827 rows x 3 columns]

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

In [24]:
vol = vol.resample('W').mean()
vol

Ticker             AAPL        IBM        TSLA
Date
2015-01-04  212818400.0  5779673.0  71466000.0
2015-01-11  226602000.0  5115776.8  68128800.0
2015-01-18  243381280.0  4865950.2  92397600.0
2015-01-25  198737000.0  8170515.5  60793875.0
2015-02-01  372674160.0  6888537.8  47160600.0
...                 ...        ...         ...
2026-03-08   42195700.0  7078940.0  60398320.0
2026-03-15   34550440.0  4991840.0  61663080.0
2026-03-22   44677780.0  6450980.0  60303760.0
2026-03-29   40774360.0  4358380.0  61471360.0
2026-04-05   44497900.0  4314800.0  71621850.0

[588 rows x 3 columns]

### Step 9. Find all the volume traded in the year of 2015

In [27]:
vol.query('Date > 2016').sum()

Ticker
AAPL    5.368782e+10
IBM     2.586291e+09
TSLA    6.112661e+10
dtype: float64

### BONUS: Create your own question and answer it.