# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [14]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [15]:
url = "https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv"
called = pd.read_csv(url)
called

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN
...,...,...,...,...,...,...,...,...,...
113,2026-02-25,62363,NaN,27334,NaN,8279,NaN,19054,NaN
114,2026-03-04,24299,NaN,12227,NaN,-652,NaN,12879,NaN
115,2026-03-11,22797,NaN,11869,NaN,4291,NaN,7578,NaN
116,2026-03-18,25057,NaN,12807,NaN,2823,NaN,9984,NaN
117,2026-03-25,40513,NaN,31891,NaN,29748,NaN,2143,NaN

### Step 4.  What is the frequency of the dataset?

### Step 5. Set the column Date as the index.

In [16]:
called = called.set_index('Date')
called

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN
...,...,...,...,...,...,...,...,...
2026-02-25,62363,NaN,27334,NaN,8279,NaN,19054,NaN
2026-03-04,24299,NaN,12227,NaN,-652,NaN,12879,NaN
2026-03-11,22797,NaN,11869,NaN,4291,NaN,7578,NaN
2026-03-18,25057,NaN,12807,NaN,2823,NaN,9984,NaN
2026-03-25,40513,NaN,31891,NaN,29748,NaN,2143,NaN

### Step 6. What is the type of the index?

In [17]:
called.index
# It is a string type

Index(['2022-07-06', '2022-07-13', '2022-07-20', '2022-07-27', '2022-08-03',
       '2022-08-10', '2022-08-17', '2022-08-24', '2022-08-31', '2022-09-07',
       ...
       '2025-10-01', '2025-10-08', '2026-02-04', '2026-02-11', '2026-02-18',
       '2026-02-25', '2026-03-04', '2026-03-11', '2026-03-18', '2026-03-25'],
      dtype='str', name='Date', length=118)

### Step 7. Set the index to a DatetimeIndex type

In [ ]:
called.index = pd.to_datetime(called.index)

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [19]:
called = called.resample('ME').sum()
called

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48596,0.0,32348,0.0,33705,0.0,-1357,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0
2022-12-31,40451,0.0,29124,0.0,18273,0.0,10849,0.0
2023-01-31,34891,0.0,7849,0.0,-9996,0.0,17845,0.0
2023-02-28,13284,0.0,16508,0.0,6243,0.0,10264,0.0
2023-03-31,28861,0.0,3713,0.0,2500,0.0,1213,0.0
2023-04-30,39723,0.0,19058,0.0,14426,0.0,4632,0.0
2023-05-31,23789,0.0,6377,0.0,2020,0.0,4358,0.0
2023-06-30,62390,0.0,50665,0.0,39254,0.0,11408,0.0
2023-07-31,63164,0.0,46019,0.0,38479,0.0,7539,0.0
2023-08-31,18730,0.0,11967,0.0,10880,0.0,1089,0.0
2023-09-30,37875,0.0,29963,0.0,29830,0.0,133,0.0
2023-10-31,27572,0.0,13947,0.0,14375,0.0,-429,0.0
2023-11-30,114386,0.0,78843,0.0,73411,0.0,5433,0.0
2023-12-31,112558,0.0,99097,0.0,80368,0.0,18729,0.0
2024-01-31,58942,0.0,36802,0.0,30780,0.0,6022,0.0
2024-02-29,44261,0.0,36069,0.0,27252,0.0,8818,0.0
2024-03-31,105578,0.0,87666,0.0,76618,0.0,11047,0.0
2024-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-05-31,79344,0.0,51938,0.0,42353,0.0,9584,0.0
2024-06-30,79138,0.0,51872,0.0,39741,0.0,12131,0.0
2024-07-31,134078,0.0,98285,0.0,95686,0.0,2598,0.0
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2025-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-06-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-07-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-09-30,125005,0.0,72886,0.0,48603,0.0,24282,0.0
2025-10-31,79460,0.0,53892,0.0,42312,0.0,11580,0.0
2025-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-02-28,183633,0.0,108383,0.0,49608,0.0,58774,0.0
2026-03-31,112666,0.0,68794,0.0,36210,0.0,32584,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [20]:
called = called.dropna()
called

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257,0.0,15635,0.0,11090,0.0,4545,0.0
2022-08-31,48596,0.0,32348,0.0,33705,0.0,-1357,0.0
2022-09-30,13775,0.0,10324,0.0,11629,0.0,-1305,0.0
2022-10-31,82879,0.0,55644,0.0,47435,0.0,8209,0.0
2022-11-30,82731,0.0,54314,0.0,37348,0.0,16967,0.0
2022-12-31,40451,0.0,29124,0.0,18273,0.0,10849,0.0
2023-01-31,34891,0.0,7849,0.0,-9996,0.0,17845,0.0
2023-02-28,13284,0.0,16508,0.0,6243,0.0,10264,0.0
2023-03-31,28861,0.0,3713,0.0,2500,0.0,1213,0.0
2023-04-30,39723,0.0,19058,0.0,14426,0.0,4632,0.0
2023-05-31,23789,0.0,6377,0.0,2020,0.0,4358,0.0
2023-06-30,62390,0.0,50665,0.0,39254,0.0,11408,0.0
2023-07-31,63164,0.0,46019,0.0,38479,0.0,7539,0.0
2023-08-31,18730,0.0,11967,0.0,10880,0.0,1089,0.0
2023-09-30,37875,0.0,29963,0.0,29830,0.0,133,0.0
2023-10-31,27572,0.0,13947,0.0,14375,0.0,-429,0.0
2023-11-30,114386,0.0,78843,0.0,73411,0.0,5433,0.0
2023-12-31,112558,0.0,99097,0.0,80368,0.0,18729,0.0
2024-01-31,58942,0.0,36802,0.0,30780,0.0,6022,0.0
2024-02-29,44261,0.0,36069,0.0,27252,0.0,8818,0.0
2024-03-31,105578,0.0,87666,0.0,76618,0.0,11047,0.0
2024-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-05-31,79344,0.0,51938,0.0,42353,0.0,9584,0.0
2024-06-30,79138,0.0,51872,0.0,39741,0.0,12131,0.0
2024-07-31,134078,0.0,98285,0.0,95686,0.0,2598,0.0
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-02-28,0,0.0,0,0.0,0,0.0,0,0.0
2025-03-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-04-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-05-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-06-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-07-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2025-09-30,125005,0.0,72886,0.0,48603,0.0,24282,0.0
2025-10-31,79460,0.0,53892,0.0,42312,0.0,11580,0.0
2025-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2025-12-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2026-02-28,183633,0.0,108383,0.0,49608,0.0,58774,0.0
2026-03-31,112666,0.0,68794,0.0,36210,0.0,32584,0.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [22]:
called = called.resample('YE').sum()
called

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-12-31,303689,0.0,197389,0.0,159480,0.0,37908,0.0
2023-12-31,577223,0.0,384006,0.0,301790,0.0,82214,0.0
2024-12-31,501341,0.0,362632,0.0,312430,0.0,50200,0.0
2025-12-31,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-12-31,296299,0.0,177177,0.0,85818,0.0,91358,0.0

### BONUS: Create your own question and answer it.