In [1]:
import pandas as pd
import numpy as np

In [2]:
val1 = np.array([1,None,2,3])
val1

array([1, None, 2, 3], dtype=object)

In [3]:
%timeit np.arange(156, dtype=int).sum()

1.56 μs ± 29.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [4]:
%timeit np.arange(156, dtype=object).sum()

4.41 μs ± 173 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [ ]:
val1.sum() # Unable to do sum due to None

In [6]:
val2 = np.array([1,np.nan,2,3])
val2

array([ 1., nan,  2.,  3.])

In [ ]:
val2.sum()

np.float64(nan)

In [9]:
val2.min()

np.float64(nan)

In [10]:
np.nansum(val2), np.nanmin(val2)

(np.float64(6.0), np.float64(1.0))

In [11]:
x = pd.Series(range(2), dtype=int)  
x

0    0
1    1
dtype: int64

In [12]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [15]:
pd.Series([1,np.nan,2,None,3])

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

Detecting null values

In [17]:
data = pd.Series([1,3,5,6,np.nan,'Hello',None])
data

0        1
1        3
2        5
3        6
4      NaN
5    Hello
6     None
dtype: object

In [20]:
data.isna()

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [21]:
data[data.notnull()]

0        1
1        3
2        5
3        6
5    Hello
dtype: object

In [23]:
data.dropna()

0        1
1        3
2        5
3        6
5    Hello
dtype: object

In [25]:
data

0        1
1        3
2        5
3        6
4      NaN
5    Hello
6     None
dtype: object

In [26]:
sum(data.isnull())

2

In [29]:
df = pd.DataFrame([[1,np.nan,2],[2,3,5],[np.nan,6,7]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  6.0  7

In [30]:
df.dropna()

     0    1  2
1  2.0  3.0  5

In [31]:
df.dropna(axis = 1)

   2
0  2
1  5
2  7

In [33]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  6.0  7 NaN

In [34]:
df.dropna(axis = 'columns',how='all')

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  6.0  7

In [35]:
df.dropna(axis = 'columns',how='any')

   2
0  2
1  5
2  7

In [36]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'), dtype='Int32')
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [41]:
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [38]:
data.ffill()

a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [39]:
data.bfill()

a    1
b    2
c    2
d    3
e    3
dtype: Int32