In [8]:
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.1'

Panda series object

In [5]:
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[2]

np.float64(0.75)

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

Series as generalized NumPy array

In [13]:
data = pd.Series([0.25,0.5,0.75,1], index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data['c']

np.float64(0.75)

Series as a dictionary

In [15]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
population['Texas']

np.int64(26448193)

In [17]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

In [18]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [19]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: str

DataFrame Object

In [20]:
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}

In [22]:
states = pd.DataFrame({'population':population, 'area':area_dict})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [24]:
states.population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [27]:
pd.DataFrame(population,columns = ['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [30]:
np.arange(3)

array([0, 1, 2])

In [29]:
data = [{'a':i, 'b': 2 * i} for i in range(3)]
print(data)

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [32]:
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [33]:
np.random.rand(3,2)

array([[0.7836784 , 0.37078348],
       [0.74350788, 0.77581795],
       [0.47302641, 0.03301654]])

In [35]:
pd.DataFrame(np.random.rand(3,2), columns=[1,2],index=['a','b','c'])

          1         2
a  0.006050  0.612633
b  0.410836  0.723750
c  0.600020  0.340115

Pandas Index Object

In [37]:
ind = pd.Index([2,3,5,7,11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [41]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,5,7,11,13])

In [45]:
indA.intersection(indB)

Index([5, 7], dtype='int64')

In [47]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11, 13], dtype='int64')

In [ ]:
data = pd.Series([1,2,3,4,5,6,7], index = ['a','b','c','d','e','f','g'])
data

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [50]:
data['c']

np.int64(3)

In [51]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

In [52]:
list(data.items())

[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7)]

In [54]:
data[0:4]

a    1
b    2
c    3
d    4
dtype: int64

loc and iloc

In [58]:
data = pd.Series(['a','b','c','d','e','f','g'], index = [1,2,3,4,5,6,7])
data

1    a
2    b
3    c
4    d
5    e
6    f
7    g
dtype: str

In [65]:
data.loc[1]

'a'

In [60]:
data.iloc[1]

'b'

In [62]:
data.iloc[2:5]

3    c
4    d
5    e
dtype: str

In [ ]:
data.T # Transpose

1    a
2    b
3    c
4    d
5    e
6    f
7    g
dtype: str

In [74]:
states['density'] = states['population']/states['area']
print(states.iloc[0:2,0])
states

California    38332521
Texas         26448193
Name: population, dtype: int64

            population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763