Combining Datasets: Concat and Append

In [1]:
import pandas as pd
import numpy as np

In [3]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC',range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [7]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)

    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

In [5]:
series_1 = pd.Series(['A','B','C'], index = [1,2,3])
series_2 = pd.Series(['D','E','F'], index = [1,2,3])

pd.concat([series_1,series_2])

1    A
2    B
3    C
1    D
2    E
3    F
dtype: str

In [8]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])
display("df1","df2","pd.concat([df1,df2])")

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1,df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [12]:
df1 = make_df('AB',[1,2])
df2 = make_df('CD',[1,2])
display("df1","df2","pd.concat([df1,df2], axis=1)")

df1
    A   B
1  A1  B1
2  A2  B2

df2
    C   D
1  C1  D1
2  C2  D2

pd.concat([df1,df2], axis=1)
    A   B   C   D
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [15]:
df1 = make_df('AB',[0,1])
df2 = make_df('AB',[2,3])

df2.index = df1.index
display("df1","df2","pd.concat([df1,df2])")

df1
    A   B
0  A0  B0
1  A1  B1

df2
    A   B
0  A2  B2
1  A3  B3

pd.concat([df1,df2])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [16]:
try:
    pd.concat([df1,df2], verify_integrity = True)
except ValueError as e:
    print("ValueError", e)

ValueError Indexes have overlapping values: Index([0, 1], dtype='int64')

In [18]:
display("df1","df2","pd.concat([df1,df2], ignore_index = True)")

df1
    A   B
0  A0  B0
1  A1  B1

df2
    A   B
0  A2  B2
1  A3  B3

pd.concat([df1,df2], ignore_index = True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [24]:
display('df1', 'df2', 'pd.concat([df1, df2], keys=["df1", "df2"])')

df1
    A   B
0  A0  B0
1  A1  B1

df2
    A   B
0  A2  B2
1  A3  B3

pd.concat([df1, df2], keys=["df1", "df2"])
        A   B
df1 0  A0  B0
    1  A1  B1
df2 0  A2  B2
    1  A3  B3

In [26]:
df3 = make_df('ABC',[1,2])
df4 = make_df('BCD',[3,4])

display('df3', 'df4', 'pd.concat([df3, df4])')

df3
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df4
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df3, df4])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [28]:
display('df3', 'df4', 'pd.concat([df3, df4], join = "inner")')

df3
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df4
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df3, df4], join = "inner")
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [29]:
pd.concat([df3, df4.reindex(df3.columns, axis = 1)])

     A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

Merge and joins

In [30]:
df1 = pd.DataFrame({'employee':['Bob','Lake','Lisa','Sue'],'group':['Accounting','Engineering','Engineering','HR']})
df2 = pd.DataFrame({'employee':['Lisa','Bob','Lake','Sue'],'hire_date':[2004,2008,2012,2014]})
display('df1','df2')

df1
  employee        group
0      Bob   Accounting
1     Lake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Lake       2012
3      Sue       2014

In [31]:
df3 = pd.merge(df1,df2)
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Lake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [33]:
df4 = pd.DataFrame({'group':['Accounting','Engineering','HR'], 'supervisor':['John','Doe','Mike']})
display('df3','df4')

df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Lake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

df4
         group supervisor
0   Accounting       John
1  Engineering        Doe
2           HR       Mike

In [34]:
pd.merge(df3,df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008       John
1     Lake  Engineering       2012        Doe
2     Lisa  Engineering       2004        Doe
3      Sue           HR       2014       Mike

In [35]:
df5 = pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],'skills': ['math','spreadsheets','software','math','spreasheets','communication']})
display('df4','df5','pd.merge(df4,df5)')

df4
         group supervisor
0   Accounting       John
1  Engineering        Doe
2           HR       Mike

df5
         group         skills
0   Accounting           math
1   Accounting   spreadsheets
2  Engineering       software
3  Engineering           math
4           HR    spreasheets
5           HR  communication

pd.merge(df4,df5)
         group supervisor         skills
0   Accounting       John           math
1   Accounting       John   spreadsheets
2  Engineering        Doe       software
3  Engineering        Doe           math
4           HR       Mike    spreasheets
5           HR       Mike  communication

In [36]:
display('df1','df2')

df1
  employee        group
0      Bob   Accounting
1     Lake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Lake       2012
3      Sue       2014

In [37]:
display('df1','df2','pd.merge(df1,df2, on="employee")')

df1
  employee        group
0      Bob   Accounting
1     Lake  Engineering
2     Lisa  Engineering
3      Sue           HR

df2
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Lake       2012
3      Sue       2014

pd.merge(df1,df2, on="employee")
  employee        group  hire_date
0      Bob   Accounting       2008
1     Lake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [40]:
df6 = pd.DataFrame({'name':['Bob','Lake','Lisa','Sue'], 'salary':[70000,80000,90000,100000]})
display('df1','df6','pd.merge(df1,df6, left_on="employee", right_on = "name")')

df1
  employee        group
0      Bob   Accounting
1     Lake  Engineering
2     Lisa  Engineering
3      Sue           HR

df6
   name  salary
0   Bob   70000
1  Lake   80000
2  Lisa   90000
3   Sue  100000

pd.merge(df1,df6, left_on="employee", right_on = "name")
  employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Lake  Engineering  Lake   80000
2     Lisa  Engineering  Lisa   90000
3      Sue           HR   Sue  100000

In [41]:
display('df1','df6','pd.merge(df1,df6, left_on="employee", right_on = "name").drop(columns="name")')

df1
  employee        group
0      Bob   Accounting
1     Lake  Engineering
2     Lisa  Engineering
3      Sue           HR

df6
   name  salary
0   Bob   70000
1  Lake   80000
2  Lisa   90000
3   Sue  100000

pd.merge(df1,df6, left_on="employee", right_on = "name").drop(columns="name")
  employee        group  salary
0      Bob   Accounting   70000
1     Lake  Engineering   80000
2     Lisa  Engineering   90000
3      Sue           HR  100000

In [45]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

display('df1a', 'df2a')

df1a
                group
employee
Bob        Accounting
Lake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee
Lisa           2004
Bob            2008
Lake           2012
Sue            2014

In [46]:
display('df1a','df2a','pd.merge(df1a,df2a,left_index = True,right_index = True)')

df1a
                group
employee
Bob        Accounting
Lake      Engineering
Lisa      Engineering
Sue                HR

df2a
          hire_date
employee
Lisa           2004
Bob            2008
Lake           2012
Sue            2014

pd.merge(df1a,df2a,left_index = True,right_index = True)
                group  hire_date
employee
Bob        Accounting       2008
Lake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [48]:
display('df1a','df3','pd.merge(df1a,df3,left_index = True,right_on = "employee")')

df1a
                group
employee
Bob        Accounting
Lake      Engineering
Lisa      Engineering
Sue                HR

df3
  employee        group  hire_date
0      Bob   Accounting       2008
1     Lake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

pd.merge(df1a,df3,left_index = True,right_on = "employee")
       group_x employee      group_y  hire_date
0   Accounting      Bob   Accounting       2008
1  Engineering     Lake  Engineering       2012
2  Engineering     Lisa  Engineering       2004
3           HR      Sue           HR       2014

In [53]:
df7 = pd.DataFrame({'name':['Peter','Paul','Mary'],'food':['fish','beans','bread']},columns = ['name','food'])
df8 = pd.DataFrame({'name':['Mary','Joseph'],'drink':['wine','bear']},columns = ['name','drink'])
display('df7','df8','pd.merge(df7,df8,how = "outer")')

df7
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df8
     name drink
0    Mary  wine
1  Joseph  bear

pd.merge(df7,df8,how = "outer")
     name   food drink
0  Joseph    NaN  bear
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

In [55]:
display('df7','df8','pd.merge(df7,df8,how = "left")')

df7
    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

df8
     name drink
0    Mary  wine
1  Joseph  bear

pd.merge(df7,df8,how = "left")
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [59]:
df9 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'], 'rank':[1,2,3,4]})
df10 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'], 'rank':[3,1,4,2]})

display('df9','df10','pd.merge(df9,df10,left_on="name",right_on="name")')

df9
   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4

df10
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2

pd.merge(df9,df10,left_on="name",right_on="name")
   name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [66]:
pop = pd.read_csv('state-population.csv')
areas = pd.read_csv('state-areas.csv')
abbrevs = pd.read_csv('state-abbrevs.csv')

display('pop.head()','areas.head()','abbrevs.head()')

pop.head()
  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0
3           AL    total  2010   4785570.0
4           AL  under18  2011   1125763.0

areas.head()
        state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

abbrevs.head()
        state abbreviation
0     Alabama           AL
1      Alaska           AK
2     Arizona           AZ
3    Arkansas           AR
4  California           CA

In [91]:
state_and_abbr = pd.merge(pop,abbrevs,how = "outer",left_on = "state/region",right_on = "abbreviation")
all = pd.merge(state_and_abbr,areas,how = "left",on = "state")
all

,state/region,ages,year,population,state,abbreviation,area (sq. mi)
0,AK,total,1990,553290.0,Alaska,AK,656425.0
1,AK,under18,1990,177502.0,Alaska,AK,656425.0
2,AK,total,1992,588736.0,Alaska,AK,656425.0
3,AK,under18,1991,182180.0,Alaska,AK,656425.0
4,AK,under18,1992,184878.0,Alaska,AK,656425.0
...,...,...,...,...,...,...,...
2539,WY,under18,1993,137458.0,Wyoming,WY,97818.0
2540,WY,total,1991,459260.0,Wyoming,WY,97818.0
2541,WY,under18,1991,136720.0,Wyoming,WY,97818.0
2542,WY,under18,1990,136078.0,Wyoming,WY,97818.0
2543,WY,total,1990,453690.0,Wyoming,WY,97818.0

In [92]:
all.isnull().sum()

state/region      0
ages              0
year              0
population       20
state            96
abbreviation     96
area (sq. mi)    96
dtype: int64

In [93]:
all[['population']]

      population
0       553290.0
1       177502.0
2       588736.0
3       182180.0
4       184878.0
...          ...
2539    137458.0
2540    459260.0
2541    136720.0
2542    136078.0
2543    453690.0

[2544 rows x 1 columns]

In [94]:
all[all['population'].isnull()].head()

     state/region     ages  year  population state abbreviation  area (sq. mi)
1872           PR  under18  1990         NaN   NaN          NaN            NaN
1873           PR    total  1990         NaN   NaN          NaN            NaN
1874           PR    total  1991         NaN   NaN          NaN            NaN
1875           PR  under18  1991         NaN   NaN          NaN            NaN
1876           PR    total  1993         NaN   NaN          NaN            NaN

In [95]:
all.loc[all['state'].isnull(),'state/region'].unique()

<StringArray>
['PR', 'USA']
Length: 2, dtype: str

In [96]:
all.loc[all['state/region'] == 'PR', 'state'] =  'Puerto Rico'
all.loc[all['state/region'] == 'USA','state']  = 'United States'

all.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
abbreviation     96
area (sq. mi)    96
dtype: int64

In [ ]:
all = all.drop(columns = ["abbreviation"])

In [101]:
all.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
area (sq. mi)    96
dtype: int64

In [103]:
all['state'][all['area (sq. mi)'].isnull()].unique()

<StringArray>
['Puerto Rico', 'United States']
Length: 2, dtype: str

In [104]:
all.dropna(inplace = True)
all.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

     state/region     ages  year  population    state  area (sq. mi)
0              AK    total  1990    553290.0   Alaska       656425.0
1              AK  under18  1990    177502.0   Alaska       656425.0
2              AK    total  1992    588736.0   Alaska       656425.0
3              AK  under18  1991    182180.0   Alaska       656425.0
4              AK  under18  1992    184878.0   Alaska       656425.0
...           ...      ...   ...         ...      ...            ...
2539           WY  under18  1993    137458.0  Wyoming        97818.0
2540           WY    total  1991    459260.0  Wyoming        97818.0
2541           WY  under18  1991    136720.0  Wyoming        97818.0
2542           WY  under18  1990    136078.0  Wyoming        97818.0
2543           WY    total  1990    453690.0  Wyoming        97818.0

[2448 rows x 6 columns]

In [112]:
data2010 = all.query("year == 2010 & ages == 'total'")
data2010

,state/region,ages,year,population,state,area (sq. mi)
43,AK,total,2010,713868.0,Alaska,656425.0
51,AL,total,2010,4785570.0,Alabama,52423.0
141,AR,total,2010,2922280.0,Arkansas,53182.0
149,AZ,total,2010,6408790.0,Arizona,114006.0
197,CA,total,2010,37333601.0,California,163707.0
283,CO,total,2010,5048196.0,Colorado,104100.0
293,CT,total,2010,3579210.0,Connecticut,5544.0
341,DC,total,2010,605125.0,District of Columbia,68.0
427,DE,total,2010,899711.0,Delaware,1954.0
475,FL,total,2010,18846054.0,Florida,65758.0
485,GA,total,2010,9713248.0,Georgia,59441.0
570,HI,total,2010,1363731.0,Hawaii,10932.0
618,IA,total,2010,3050314.0,Iowa,56276.0
629,ID,total,2010,1570718.0,Idaho,83574.0
714,IL,total,2010,12839695.0,Illinois,57918.0
725,IN,total,2010,6489965.0,Indiana,36420.0
773,KS,total,2010,2858910.0,Kansas,82282.0
858,KY,total,2010,4347698.0,Kentucky,40411.0
869,LA,total,2010,4545392.0,Louisiana,51843.0
954,MA,total,2010,6563263.0,Massachusetts,10555.0
965,MD,total,2010,5787193.0,Maryland,12407.0
1050,ME,total,2010,1327366.0,Maine,35387.0
1061,MI,total,2010,9876149.0,Michigan,96810.0
1146,MN,total,2010,5310337.0,Minnesota,86943.0
1194,MO,total,2010,5996063.0,Missouri,69709.0
1205,MS,total,2010,2970047.0,Mississippi,48434.0
1253,MT,total,2010,990527.0,Montana,147046.0
1338,NC,total,2010,9559533.0,North Carolina,53821.0
1349,ND,total,2010,674344.0,North Dakota,70704.0
1434,NE,total,2010,1829838.0,Nebraska,77358.0
1482,NH,total,2010,1316614.0,New Hampshire,9351.0
1493,NJ,total,2010,8802707.0,New Jersey,8722.0
1578,NM,total,2010,2064982.0,New Mexico,121593.0
1589,NV,total,2010,2703230.0,Nevada,110567.0
1637,NY,total,2010,19398228.0,New York,54475.0
1722,OH,total,2010,11545435.0,Ohio,44828.0
1733,OK,total,2010,3759263.0,Oklahoma,69903.0
1818,OR,total,2010,3837208.0,Oregon,98386.0
1829,PA,total,2010,12710472.0,Pennsylvania,46058.0
1962,RI,total,2010,1052669.0,Rhode Island,1545.0
1973,SC,total,2010,4636361.0,South Carolina,32007.0
2058,SD,total,2010,816211.0,South Dakota,77121.0
2069,TN,total,2010,6356683.0,Tennessee,42146.0
2154,TX,total,2010,25245178.0,Texas,268601.0
2213,UT,total,2010,2774424.0,Utah,84904.0
2261,VA,total,2010,8024417.0,Virginia,42769.0
2346,VT,total,2010,625793.0,Vermont,9615.0
2394,WA,total,2010,6742256.0,Washington,71303.0
2442,WI,total,2010,5689060.0,Wisconsin,65503.0
2453,WV,total,2010,1854146.0,West Virginia,24231.0
2501,WY,total,2010,564222.0,Wyoming,97818.0

In [113]:
data2010.set_index('state', inplace=True)
density = data2010['population'] / data2010['area (sq. mi)']

In [114]:
density

state
Alaska                     1.087509
Alabama                   91.287603
Arkansas                  54.948667
Arizona                   56.214497
California               228.051342
Colorado                  48.493718
Connecticut              645.600649
District of Columbia    8898.897059
Delaware                 460.445752
Florida                  286.597129
Georgia                  163.409902
Hawaii                   124.746707
Iowa                      54.202751
Idaho                     18.794338
Illinois                 221.687472
Indiana                  178.197831
Kansas                    34.745266
Kentucky                 107.586994
Louisiana                 87.676099
Massachusetts            621.815538
Maryland                 466.445797
Maine                     37.509990
Michigan                 102.015794
Minnesota                 61.078373
Missouri                  86.015622
Mississippi               61.321530
Montana                    6.736171
North Carolina           177.617157
North Dakota               9.537565
Nebraska                  23.654153
New Hampshire            140.799273
New Jersey              1009.253268
New Mexico                16.982737
Nevada                    24.448796
New York                 356.094135
Ohio                     257.549634
Oklahoma                  53.778278
Oregon                    39.001565
Pennsylvania             275.966651
Rhode Island             681.339159
South Carolina           144.854594
South Dakota              10.583512
Tennessee                150.825298
Texas                     93.987655
Utah                      32.677188
Virginia                 187.622273
Vermont                   65.085075
Washington                94.557817
Wisconsin                 86.851900
West Virginia             76.519582
Wyoming                    5.768079
dtype: float64