In [3]:
import pandas as pd
import numexpr as ne

In [4]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 22],
    'Department': ['HR', 'IT', 'IT', 'Finance', 'HR'],
    'Salary': [50000, 80000, 120000, 90000, 45000]
}
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   25         HR   50000
1      Bob   30         IT   80000
2  Charlie   35         IT  120000
3    David   40    Finance   90000
4      Eve   22         HR   45000

In [ ]:
over_30 = df.query("Age > 30")

In [5]:
over_30

      Name  Age Department  Salary
2  Charlie   35         IT  120000
3    David   40    Finance   90000

In [6]:
df[(df['Department'] == 'IT') & (df['Salary'] > 100000)]

      Name  Age Department  Salary
2  Charlie   35         IT  120000

In [7]:
it_high_tier = df.query("Department == 'IT' and Salary > 100000")
it_high_tier

      Name  Age Department  Salary
2  Charlie   35         IT  120000

In [11]:
min_salary = 60000
well_paid = df.query("Salary >= @min_salary")
well_paid

      Name  Age Department  Salary
1      Bob   30         IT   80000
2  Charlie   35         IT  120000
3    David   40    Finance   90000